#name: Deploy Development
#
#on:
#  push:
#    branches:
#      - development
#
#jobs:
#  verify:
#    uses: ./.github/workflows/verify.yml
#    secrets:
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#  deploy:
#    uses: ./.github/workflows/deploy.yml
#    needs: verify
#    with:
#      env: development
#      url: https://boiling-shore-06894-dev.herokuapp.com/
#    secrets:
#      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#      JIRA_URL: ${{ secrets.JIRA_URL }}
#      JIRA_CLIENT_ID: ${{ secrets.JIRA_CLIENT_ID }}
#      JIRA_CLIENT_SECRET: ${{ secrets.JIRA_CLIENT_SECRET }}
