coverage:
  status:
    project:
      frontend:
        target: 40%
        flags:
          - frontend
      backend-ut:
        target: 70%
        flags:
          - backend-ut
      backend-it:
        target: 10%
        flags:
          - backend-it
    patch:
      default:
        informational: true
flags:
  frontend:
    paths:
      - src/apps/app/src
  backend-ut:
    paths:
      - src/apps/api/src/main/java
  backend-it:
    paths:
      - src/apps/api/src/main/java
