version: '3.9'
services:
  postgres:
    env_file: .env
    image: postgres
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
    volumes:
      - data:/var/lib/postgresql/data/
  mailhog:
    image: mailhog/mailhog
    ports:
      - '3025:1025'
      - '8025:8025'
    restart: 'unless-stopped'
volumes:
  data:
