version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '18888:8888'
    restart: 'unless-stopped'
    volumes:
      - data:/var/lib/postgresql/data/
volumes:
  data:
