version: "3.9"
services:
  postgres:
    env_file:
      .env
    image: postgres
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
    volumes:
      - data:/var/lib/postgresql/data/
volumes:
  data:
