application:
  public_urls:
    - /
    - /index.html
    - /app/**
    - /api
    - /api/auth/login
    - /api/auth/signup
    - /api/auth/token
    - /api/auth/activate
    - /websocket/**
    - /api/cypress/**
  run_data_init: false
