application:
  jwt:
    secret: ${JWT_SECRET:'secret'}
  run_data_init: true
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
server:
  port: ${PORT}
