application:
  jwt:
    secret: ${JWT_SECRET:'secret'}
  host_url: 'https://${HEROKU_APP_NAME}.herokuapp.com/app' # https://devcenter.heroku.com/articles/dyno-metadata
  run_data_init: true
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
server:
  port: ${PORT}
