application:
  public_urls:
    - /
    - /index.html
    - /app/**
    - /api
    - /api/auth/login
    - /api/auth/signup
    - /api/activation/token
    - /api/activation/activate
    - /explorer/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /v*/api-docs/**
spring:
  mail:
    host: localhost
    port: 1025
    properties.mail.smtp.auth: false
    properties.mail.smtp.starttls.enable: false
  devtools:
    livereload:
      enabled: true
springfox:
  documentation:
    enabled: true
