application:
  host_url: 'https://boiling-shore-06894.herokuapp.com'
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
server:
  port: ${PORT}
