application:
  public_urls:
    - /
    - /index.html
    - /app/**
    - /api
    - /api/auth/login
    - /api/auth/signup
    - /api/auth/token
    - /api/auth/activate
  jwt:
    secret: 'ieWCbSL5dcp3HgWkH2RSEdPGje7jjaM1Lt0jtYnHkml1WVcA6bIHKPi6cHEXWFmaECPkYWtlU85qCE2QC2ZrLlxmk29rFGgDrN8FlezGcrSH0V0ilMtuMnhmvJAvGmLlBZ90sikgYZWaZaWirI4TIUrDThJ6nTFEmRfDaE3ISPZVNr24HsxfmrK9rAqczoeKfpbjRGAE'
  host_url: 'localhost'
server:
  port: 8888
  error:
    whitelabel:
      enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: p@ssw0rd
    username: master
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: false
  flyway:
    enabled: true
    # flyway's table schema_version shall be in the same schema as the other tables
    schemas: ${spring.jpa.properties.hibernate.default_schema}
    table: flyway_schema_version
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: application
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

springfox:
  documentation:
    enabled: false

logging:
  file:
    name: logs/logs.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
