application:
  jwt:
    secret: '${JWT_SECRET}'
  host_url: 'https://boiling-shore-06894.herokuapp.com/app'
  run_data_init: true
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
server:
  port: ${PORT}
