application:
  public_urls:
    - /
    - /index.html
    - /app/**
    - /api
    - /api/auth/login
    - /api/auth/signup
    - /explorer/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /v*/api-docs/**
spring:
  devtools:
    livereload:
      enabled: true
springfox:
  documentation:
    enabled: true
