spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chess
    password: p@ssw0rd
    username: master
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: chess
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
