name: Cancel Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cancel-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Determine Release Version
        id: release-version
        run: |
          version=$(node --print "require('./package.json').version")
          echo "version=${version%-SNAPSHOT}" >> $GITHUB_OUTPUT

      - name: Delete Branches and Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --delete release/${{ steps.release-version.outputs.version }} &>/dev/null
          git push origin --delete merge-back/${{ steps.release-version.outputs.version }} &>/dev/null
          git push origin --delete ${{ steps.release-version.outputs.version }} &>/dev/null
