name: Cancel Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cancel-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Determine Release Version
        id: release-version
        run: |
          version=$(node --print "require('./package.json').version")
          echo "version=${version%-SNAPSHOT}" >> $GITHUB_OUTPUT

      - name: Delete Release Tag
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --delete ${{ steps.release-version.outputs.version }}

      - name: Delete Release Branch
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --delete release/${{ steps.release-version.outputs.version }}

      - name: Delete Merge Back Branch
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --delete merge-back/${{ steps.release-version.outputs.version }}
