name: Verify

on:
  push:
    branches-ignore:
      - master
      - development
  pull_request:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      dependabot-run: ${{ github.actor == 'dependabot[bot]' }}
      upload-dev-artifacts: ${{ github.ref != 'refs/heads/development' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Sync PR with target
        if: github.event_name == 'pull_request'
        run: git merge ${{ github.event.pull_request.head.sha }}

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Use Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true

      - name: Use Node 14
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'

      - name: Cache Node modules
        uses: fsancheztemprano/always-cache@main
        env:
          cache-key: ${{ runner.os }}-yarn-v2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./node
          key: ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-${{ hashFiles('**/yarn.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-${{ hashFiles('**/yarn.lock') }}-
            ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-
            ${{ env.cache-key }}-
          save-on-hit: true

      - name: Cache Maven packages
        uses: fsancheztemprano/always-cache@main
        env:
          cache-key: ${{ runner.os }}-maven-v2
        with:
          path: ~/.m2
          key: ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-${{ hashFiles('**/pom.xml') }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-${{ hashFiles('**/pom.xml') }}-
            ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-
            ${{ env.cache-key }}-
          save-on-hit: true

      - name: Cache Sonar
        uses: actions/cache@v2.1.7
        with:
          path: ~/.sonar/cache
          key: sonar

      - name: Yarn Install
        run: yarn install

      - name: Format Check
        run: npx nx format:check --all

      - name: Workspace Lint
        run: npx nx workspace-lint

      - name: Lint
        uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: lint
          all: 'true'
          parallel: 'true'

      - name: Test
        uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: test
          all: 'true'
          parallel: 'true'
          args: '--codeCoverage'

      - name: Test Jest Report
        uses: dorny/test-reporter@v1
        if: env.dependabot-run == 'false' && always()
        with:
          name: Jest Tests
          path: coverage/apps/app/jest-junit.xml
          reporter: jest-junit

      - name: Test Java Report
        uses: dorny/test-reporter@v1
        if: env.dependabot-run == 'false' && always()
        with:
          name: Java Tests
          path: apps/api/target/surefire-reports/TEST-dev.kurama.api.BackendApplicationTests.xml
          reporter: java-junit

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: env.dependabot-run == 'false' && always()
        with:
          files: |
            apps/api/target/surefire-reports/TEST-dev.kurama.api.BackendApplicationTests.xml
            coverage/apps/app/jest-junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/apps/app/lcov.info,apps/api/target/site/jacoco/jacoco.xml
          name: codecov-app
          verbose: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: env.dependabot-run == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: build
          all: 'true'
          parallel: 'true'

      - name: Upload Development Backend Artifact
        if: env.upload-dev-artifacts && env.dependabot-run == 'false'
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: apps/api/target/*.jar

      - name: Upload Development Frontend Artifact
        if: env.upload-dev-artifacts && env.dependabot-run == 'false'
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: dist/apps/app
